parameters:
#    tdt_blog.example.class: TDT\BlogBundle\Example

services:
#    tdt_blog.example:
#        class: %tdt_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
