parameters:
#    tdt_user.example.class: TDT\UserBundle\Example

services:
#    tdt_user.example:
#        class: %tdt_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
